// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjEpGDavMHDmF8UOJu-QVSUbKCdPEyy1M',
    appId: '1:974729496477:web:b735d391d741e33038d174',
    messagingSenderId: '974729496477',
    projectId: 'workorder-app-28551',
    authDomain: 'workorder-app-28551.firebaseapp.com',
    storageBucket: 'workorder-app-28551.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPDK7kL9tTZYUcB1pIQYd1l1-6LL-Hyf0',
    appId: '1:974729496477:android:bdb9d9e3b8ad444738d174',
    messagingSenderId: '974729496477',
    projectId: 'workorder-app-28551',
    storageBucket: 'workorder-app-28551.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqDviveDONB5QpnPcBsnCJfWElx-9xzdM',
    appId: '1:974729496477:ios:414f5627ff627c2938d174',
    messagingSenderId: '974729496477',
    projectId: 'workorder-app-28551',
    storageBucket: 'workorder-app-28551.firebasestorage.app',
    iosBundleId: 'com.example.workorderapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqDviveDONB5QpnPcBsnCJfWElx-9xzdM',
    appId: '1:974729496477:ios:414f5627ff627c2938d174',
    messagingSenderId: '974729496477',
    projectId: 'workorder-app-28551',
    storageBucket: 'workorder-app-28551.firebasestorage.app',
    iosBundleId: 'com.example.workorderapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjEpGDavMHDmF8UOJu-QVSUbKCdPEyy1M',
    appId: '1:974729496477:web:e32b01910744b04338d174',
    messagingSenderId: '974729496477',
    projectId: 'workorder-app-28551',
    authDomain: 'workorder-app-28551.firebaseapp.com',
    storageBucket: 'workorder-app-28551.firebasestorage.app',
  );
}
